[package]
name = "learning"
version = "0.1.0"
author = ["Dan Damian <arcassis@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5"